### ISSUE TITLE
[Meta] Refactor to WebExtension add-on

### ISSUE THREAD

**Issue by Croydon** [Croydon/vertical-tabs-reloaded#13]
Till the end of 2017 (ca. 2017-11-14, release of FF v57) add-ons need to be rewritten as WebExtensions.

This affects which Firefox version VTR will be able to support, please read: https://github.com/Croydon/vertical-tabs-reloaded/issues/13#issuecomment-271294600 for more information. When the porting to WebExtensions is done I will declare this add-on for the first time as stable, since it's eliminating all kind of crazy behavior, which wouldn't be easy till impossible in the legacy add-on form.

**Timeline:**
 * FFv53 (2017-04-19; 0.8.3): Make WebExt main settings manager, remove old settings
 * FFv55 (2017-08-08, 0.8.4): Opt-in for the new tab sidebar
 * FFv56 (2017-10-03, 0.8.5): Opt-in for the new tab sidebar
 * FFv57 (2017-11-14, 0.9.0): Not possible to use the old tab sidebar anymore

**Using the development version:**
There is already an experimental, feature incomplete WebExtension-only version [on the development channel on AMO ](https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded/) (at the end of the page). Nightly users might want to use that in the meantime.

**Roadmap:**
- [x] Embed a WebExtensions https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions (99136868, 0.8.0)
- [x] Sync SDK add-on settings with WebExt add-on settings (99136868, v0.8.0)
- [x] Manage add-on settings UI by WebExt (6f2abed, 0.8.1)
  - [x] Give settings UI again a Firefox native look&feel (80b7a51, 0.8.1)
    - [x] Re-apply when Firefox's invisible checkbox bug is fixed (and the rest works as well..)
  - [x] Add hidden add-on settings in the UI since about:config won't be possible (e896df0, 0.8.3)
- [x] Manage add-on settings by WebExt (6ad76c0, 0.8.3)
- [x] Remove settings from SDK
  - [x] VTR prefs (90d9dab, 0.8.3)
  - [x] Firefox prefs manipulation (5961484, 0.9.0)
- [x] Remove theme setting "None / Firefox default" which makes no sense anymore due to sandboxing (27bfb17, 0.8.5 + 627e93c, 0.9.0)
- [x] CSS/theme/templates
  - [x] Load templates/themes/any other css by WebExt
  - [x] Move data/ to WebExt (8b2db1c, 0.8.3)
  - [x] Remove legacy CSS like splitter (cf5c17f, 0.9.0)
- [x] Manage hotkey by WebExt (329adea, 0.8.4)
- [x] Manage Events by WebExt
  - [x] Window Events (6dcf9e0, 0.8.4)
  - [x] ~~Mouse Events~~
- [x] Manage windows by WebExt (904409b, 0.9.0)
- [x] Introduce hidden experiment add-on flag (91cd1e5, 0.8.4)
  - [x] Enforce debugging, hidden settings and experiment flag to true for Firefox Nightly (2a9a61ded, 0.8.4)
  - [x] Enforce debugging and hidden settings for Firefox Beta (80bcaea, 0.8.4)
- [x] Install, uninstall, update management regarding user data migration
  - [x] Create information page with changes in VTR and show to user once when updating to WE-only version (7bcf0ae, 0.9.0)
- [x] Add toolbar button to toggle sidebar (8f72143, 0.8.4)
- [x] Add tab browser sidebar
  - [x] Implement all visible tab features
    - [x] text label, icon, pinned tabs indication (548ec70, 6263090, 9cd36d8, 0.8.4)
    - [x] close button (ffb7f0b, 0.8.5)
    - [x] loading indication (#85, ad22ad2, 0.9.0)
    - [x] sound indication with possibility to mute/unmute (9c0a439, 0.9.0)
  - [x] Implement correct sorting of tabs - keep it dynamically up to date on tab moves (83d1e9e, 0.8.4)
    - [x] Correct tab order when opening links in new tabs (ba974b4, 0.9.0)
  - [x] Implement basic tab context menu features
    - [x] Reload, Mute, Pin Tab (3b7d7c8, 0.8.5)
    - [x] Close Tab (f3d8771, 0.8.5)
  - [x] Implement drag&drop of tabs (9417e34, 0.9.0)
  - [x] Implement tab toolbar with a new tab button (customization is a post-FFv57 issue) (0a75025, 0.8.4)
    - [x] Make it possible to place it at top, bottom and hide it completely (#57, 5b97710, 0.8.4)
  - [x] Creating new tab by clicking on free space within the tab browser (#17, 9cd36d8, 0.8.4)
  - [x] Scroll selected tabs automatically into view (789c06f, 0.8.4)
    - [x] ~~Fix #53~~
  - [x] ~~Open sidebar automatically if experiment flag is set - not possible https://bugzilla.mozilla.org/show_bug.cgi?id=1343817#c12~~~~
  - [x] ~~Hide default tab browser https://bugzilla.mozilla.org/show_bug.cgi?id=1332447 -> #128~~
- [x] Look into creating an optional WebExtension experiment for Unbranded Builds, Dev Edition and Nightly to counter combat some of the limitions of the WebExtensions APIs
  - [x] ~~Investigate if such an experiment can be installed in Beta, Nightly & Unbranded before FF57 release automatically~~

**Tracking:**
 - File read/write https://bugzilla.mozilla.org/show_bug.cgi?id=1246236

**Post-57-jobs:**
  - Hide default tab browser #128
  - Toggling of sidebar doesn't always work due to Firefox API limitations #134
  - Complete context menu options  #120
  - Discover opportunities to support ~~Firefox for Android, Chrome,~~ Opera ~~and Edge~~ #117
  - Provide API #74 
  - Rewrite some parts to use newer JavaScript (classes, modules (https://bugzilla.mozilla.org/show_bug.cgi?id=568953)

**Original:**

> ~~In order to make the code pain free and more reliable I plan to remove all XBL/XUL/XPCOM stuff and migrate it fully to SDK.~~
> ~~XBL/XUL/XPCOM will become deprecated anyway as soon as WebExtensions are more stable.~~
> ~~I am not sure yet, if the SDKs will provide all necessary functions to make something equal to the current functionality, but Mozilla will enforce to go this way in the long run anyway.~~

**Comment by Croydon** [comment]
Gradual transition to a WebExtenion will be possible and that is my current plan for VTR.

**Comment by Croydon** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions

**Comment by Croydon** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage

**Comment by Croydon** [comment]
Updated issue description.

**Comment by Croydon** [comment]
Because of the embededded WebExtension the latest Firefox ESR (45) can't be supported anymore.

**Comment by Croydon** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/getAll

**Comment by Croydon** [comment]
Release date of Firefox 51 and VTR 0.8.0 including the sync of settings between SDK/WebExt will be around 2017-01-24.

**This VTR release is critical to make sure no users will lose their settings when the full switch to WebExt will happening.**

**Comment by Croydon** [comment]
**Many APIs the full rewrite will require will only land in Firefox 53 or even later.**

**The next Firefox ESR version will be v52.**

**With other words I will break compatibility with this version very, very quickly, maybe even before the release date of v52.**

**I understand that this is critical, since Firefox ESR v52 will be the last ESR version with _full support of legacy add-ons, NPAPI support and Windows XP and Vista support_.**

**Due to a lack of time I can't do it otherwhise. And I'm trying to give my best to release a stable enough version for Firefox v52 users (the version after VTR v0.8.0) so that user of Firefox ESR v52 will be able to stay with it for the period of a year. As soon as I have pushed a version using newer APIs I also won't be able to push bug fixes for FF v52 users without downgrading all other users. So it will be really set in stone when it's not _incredible critical_ (meaning: breaking Firefox, security issues).**

**Thanks for your understanding.**

**Comment by Croydon** [comment]
VTR v0.8.0 for Firefox v51+ is now published. It contains the sync of VTR settings betweens SDK and WebExtension, preventing lose of add-on settings for Firefox ESR users, when they update from v52 to the next ESR version in 2018.

**Comment by Croydon** [comment]
Mozilla updated their release plans. FF53 gets published two weeks earlier. Making an insane timetable even more insane. Updated.

Oh Mozilla...

**Comment by Keith94** [comment]
[Bug 1208596](https://bugzilla.mozilla.org/show_bug.cgi?id=1208596) was just fixed, does this mean VTR can be implemented as a sidebar?

**Comment by Croydon** [comment]
Not really. The sidebar can't get automatically opened, can't stay open as soon as another sidebar opens, can't be automatically reopened and there is still no way to implement tabs which behave like native tabs.

**Comment by Croydon** [comment]
Similar efforts: https://github.com/piroor/treestyletab/issues/1224

**Comment by Croydon** [comment]
For the time being (currently only git versions) the window events (fullscreen) can't get fired in priviledged tabs, as a consequence the tab sidebar can't get hidden automatically. Should be fixed as soon WebExtensions sidebars are getting used.

**Comment by Croydon** [comment]
https://github.com/bwinton/StyleGuide/commit/81741b9fd91658f5adf038ecb38c7e2c89134887

**Comment by Croydon** [comment]
Pinned tab floading just broke in Nightly 55

**Comment by Croydon** [comment]
Seems like there is no way I can migrate the user specified hotkey. Will be resetted to the default then.

**Comment by Croydon** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by Croydon** [comment]
The tabbrowser toolbar will be very likely not displayed anymore in the future thanks to https://bugzilla.mozilla.org/show_bug.cgi?id=1344959

**Comment by woj-tek** [comment]
What is the impact of this change? how VTR is affected?

**Comment by Croydon** [comment]
@woj-tek 

**Too long, didn't read:** It's really hard to say.

Mozilla has set a deadline (2017-11-14, release of FF v57) without knowing by themselves in detail what APIs they want to support till then. Firefox staff seems to move on this issues in a very agile away, to say it friendly, which makes it almost impossible to properly plan transitions for all non-Firefox-staff add-on developers. Seems like we would only know things for sure 12 weeks before the release date (when FFv57 hits beta).

Several staff members have said that they want to see good support for vertical tabs solution, but the landed APIs are far away from being good enough right now.

Right now it seems like I will be required to basically implement a completely(!) new and own tab browser with all features, like drag and drop, displaying anything from favicon, title, mute sounds, close button, ALL context menu entries and features...... with high limitations e.g. I don't think it's possible to enable drag and drop between windows because of all the sandboxing. I'm also not sure yet if the APIs are allowing it to save the new tab order after drag and drop. I don't even want to start on how much time all of this will consume to recreate.

Also add-ons can't work together that easily anymore. Add-ons like Tab Mix Plus can restyle Firefox default tabs right now and this isn't lost when VTR is just moving these default Firefox tabs around and make them vertically. When VTR is required to implement a completely own tab browser, this won't be possible at all. WebExtensions are isolated from each other and from Firefox. There is no easy way that e.g. Tab Mix Plus can restyle custom implemented tabs from VTR and add context menus and do anything at all with these custom tabs.

One way is to implement custom add-on APIs (see #74) but this would require of course that all add-ons would need to use this specific API in order to be compatible with each other. Since I more or less gave up the hope for good API solutions from Mozilla I just hope that the add-on developers can agree on some kind of common API between them in order to be able to work together on (custom) tabs. If not a lot of features and (end user) customization is gone for good -or- we will have moster add-ons which need to implement EVERYTHING by their own. Also e.g. I love it when user have to possibility to use VTR and Tab Mix Plus together in a good way but it would be stupid if VTR would need to implement all of Tab Mix Plus' features as a replacement for being able to work together. And Tab Mix Plus is of course just one add-on, it would be impossible to cover all needs from all add-ons anyway.

The creator of Tree Style Tab has opened a bug which would solve many of these issues (https://bugzilla.mozilla.org/show_bug.cgi?id=1280347), however, Mozilla has closed many other bugs as WONTFIX because of the complexity of the feature request and this bug is a lot more time consuming.... so I'm expecting heavily a WONTFIX here as well. More or less the freedom WebExtensions gives us is so restrictive that we need to request APIs for almost everything which is not absolutely trivial and now Mozilla notices that developing and maintaing this APIs costs more time as they have......

Who could have known that maintaing all of the functionality of the big add-on ecosystem would require so much time.... oh wait.

Pretty much the only thing I know so far: The first few WebExtensions-only VTR versions will have less features for sure, maybe forever and the default Firefox tabbrowser toolbar (the plus symbol for opening new tabs ect.) can't be above and under the VTR tabbrowser. If they don't allow dynamically opening and closing of sidebars features like optional hiding of the tabbrowser in fullscreen are at risk and the tabbrowser may get hidden when e.g. bookmarks are opened and the tabbrowser may be needed to reopen manually.

**Comment by yfdyh000** [comment]
FYI: https://github.com/andymckay/sidebar-tabs

**Comment by woj-tek** [comment]
Thanks @Croydon Mozilla is acting strange :/

**Comment by Croydon** [comment]
I also doubt that Mozilla will enable sidebars on the right till v57, so this is another feature which will go away.

**Comment by Croydon** [comment]
Bugzilla:  Add WE API to provide functions of `SessionStore.setWindowValue` and `SessionStore.setTabValue`
 https://bugzilla.mozilla.org/show_bug.cgi?id=1322060

**Comment by Croydon** [comment]
I plan to enable the new sidebar automatically in FFv56 with an opt-out option, in order to get more feedback, before it gets enforced for good in FFv57.

**Comment by Croydon** [comment]
**Heads up: With the release of FFv53 on 2017-04-18 I will soon stop supporting FFv52 (ESR) as mentioned earlier https://github.com/Croydon/vertical-tabs-reloaded/issues/13#issuecomment-271294600**

**Comment by Croydon** [comment]
# Feedback highly appreciated.
Does anybody know a scenario where it is
a) possible and
b) reasonable
to create a new tab **WITHOUT** selecting this new tab automatically?

I'm currently reimplementing scrolling to selected/new tabs.

**Comment by mbaz** [comment]
Do you mean like opening a background tab? Middle-clicking on a link will open a new tab but does not switch to it.

Maybe you can switch to the new tab to force scrolling, then go back to the previous tab, hopefully so fast that the user doesn't notice?

**Comment by woj-tek** [comment]
I definitely open a lot of tabs in the background (especially while researching). Opening new (empty, ctrl+t) tab in the background doesn't make sense IMHO ;)

**Comment by Croydon** [comment]
Right. Background tabs will definitely be supported by the implementation. Any other scenario?

**Comment by Croydon** [comment]
![vtrheader](https://cloud.githubusercontent.com/assets/1593194/25104233/d229f8f8-23bf-11e7-9a40-76762a64ef87.PNG)


Another note: It's not possible to hide this sidebar header due to limitations of the WebExtensions APIs. Mozilla wants that users understands what elements are coming from which add-on. I don't understand this point when it comes to sidebars. I mean an user actively chooses to install an add-on which implements e.g. a vertical tabs sidebar, I'm pretty sure the user doesn't wonders afterwards when there is a vertical tabs sidebar. But whatever.

**Comment by Croydon** [comment]
As of  bf5807d the new default position for the tab toolbar is at bottom, because I'm guessing that in the WebExtension version the "header" of the tab browser would be too big when the sidebar title (https://github.com/Croydon/vertical-tabs-reloaded/issues/13#issuecomment-294589274) and the toolbar is at top.

It will still be possible to change the setting. Including hiding the tab toolbar all together (#57).

**Comment by Croydon** [comment]
So that is what Mozilla understands under "good support for vertical tabs solutions":
https://bugzilla.mozilla.org/show_bug.cgi?id=1343817#c12

They just decided that sidebars can't be opened automatically.
Meaning, that users will have to manually reopen the tab sidebar many, many times.
A catastrophe for the user experience.

To quote andym:
>* the changing of the UI in Firefox without a user action (something we've avoided as much as possible)

That is the point I'm most strongly disagree with. **The user action is to install the add-on in the first place.**

This isn't about a technical dicussion, but rather about what WebExtensions should be allowed to do.
Opening a small sidebar (can't be resized by the add-on itself, only be the user) with a clean header (user know where it's coming from) with a close button (can get rid of it any time temporary or permanent by simply uninstalling the add-on) with very limited things the sidebar can actually do **IS NOT** dangerous. Hell, Mozilla could even introduce another permission add-ons need to ask for when they want to automatically opening sidebars.

Sorry Mozilla, I don't get you.

**Comment by mbaz** [comment]
Sometimes it feels like mozilla is going the way of gnome.

**Comment by woj-tek** [comment]
This is quite bad... one of the major reasons to use Fx was the abundance of awesome plugins (and VTR/side toolbar being one of most important ones as I was using this setup since Opera 5…)... it's lighter on the resources too.
Chrome and the gang doesn't offer anything even remotely similar!

It seems that the only alternative would be Vivaldi (sic!) which integrates tabbar-positin quite nicely, but I really want to avoid using any webkit/blink related engine...

**Comment by Croydon** [comment]
I might look into creating an optional [WebExtension experiment](https://webextensions-experiments.readthedocs.io/en/latest/index.html) for Unbranded Builds, Dev Edition and Nightly to counter combat some of the limitions of the WebExtensions APIs.... No one on the release channel would benefit, though. Also it would be required to manually install it in additonal to the add-on itself.

**Comment by Croydon** [comment]
Firefox gets a setting allowing the toggeling if sidebars should be on the right or left. Downside compared to  now: It's all or nothing. Placing tabs on the other side as the other sidebars won't be possible anymore.

https://bugzilla.mozilla.org/show_bug.cgi?id=1355331

With FF56 I will make it a hidden setting in VTR to change the position. Will be naturally removed in FF57.

**Comment by grahamperrin** [comment]
> … Any other scenario?

Maybe when a new tab is opened by an application other than Firefox. When Thunderbird is in front, for example.

**Comment by Croydon** [comment]
After this Friday I will have more free time to continue working on this. 

In general I could need someone with CSS skills as I would much faster progress when I wouldn't have to deal with layouting that much.

**Comment by choller** [comment]
I've asked for help for you here: https://bugzilla.mozilla.org/show_bug.cgi?id=1387816

Please keep on developing on this, it's very valuable. If you need testers, I'm willing to try things out here :)

**Comment by Croydon** [comment]
@vdeurzen You can build VTR by using the [https://www.npmjs.com/package/jpm](JPM tool) then simply navigate to the root of the VTR git repository and type jpm xpi

**Comment by voxadam** [comment]
First of all, I love VTR. In all honesty, I don't know how I'd refactor my workflow if it were to cease existing.

I just stopped by to see if VTR was going to be able to weather the storm that the move to WebExtensions has become. This issue, #13, has done an excellent job to allay my fears. The only thing I'd say is that it might be helpful to include something in the README, and maybe even in the [AMO](https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded/?src=search), to let current and potential users that there is work underway on WebExtension version of this addon.

I was going to create a new issue for this but I decided it would be better to not pollute the tracker with endless minor things so I decided to post this here.

Again, thanks for all the hard work on this excellent addon.

**Comment by grahamperrin** [comment]
> … maybe even in the AMO, …

There already: 

>> A WebExtension version is in work! See (this issue) for more information.

**Comment by Croydon** [comment]
> A WebExtension version is in work! See (this issue) for more information.

This sentence was already in the summary after @voxadam comment I also added it to the long description and I will update also the readme. He is right, that it is critical for users to know if the add-on will just stop working or continue.

**Comment by voxadam** [comment]
Crap! I don't know how I missed that. Well, it _was_ 0300 when I commented but I should have read more carefully. Aside from the absurd hour it's entirely possible that I didn't more than glance at the AMO entry but rather headed straight to the repo and the README.

In any case, thanks for the great work. Cheers! 🍻

**Comment by eddy-geek** [comment]
Regarding May 3 comment, apparently sidebars can be opened automatically now that https://bugzilla.mozilla.org/show_bug.cgi?id=1341126 landed.

**Comment by Croydon** [comment]
## Heads up

The developer channel on AMO will soon go full WebExtension. However, this also means that this channel will soon offer an incomplete and highly instable version of the add-on. So everyone who doesn't need this version for some reason should go back to the release channel (by simply installing it from AMO again).

On the positive side: Nightly users can soon use VTR again.

**Comment by Croydon** [comment]
The developer channel [(end of page)](https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded/) has now a WebExtension-only version. While I'm in general happier when users report too much instead of too less, please be assured in this case that I'm obviously aware that almost every feature is missing right now. Thank you 😄

**Comment by grahamperrin** [comment]
> … WebExtension-only … almost every feature is missing …

The laughter! The pain!

**Comment by Croydon** [comment]
Don't worry, everything I don't explicit name within this issue as impossible or a "Post-57-job" will make it in time =)

**Comment by Croydon** [comment]
The developer channel has a new update with a close button (finally) and some other improvements, however, mostly internal refactoring at this point. I'm expecting to puslish now a lot faster updates on this channel going forward.

**The release channel will also get soon an update (v0.8.5), which is likely going to be the last update for the legacy (hybrid) version.** It will contain only small-ish changes, like a bit more contrast between the selected tab and the other tabs in the Dark&Light theme, the rest of the changes are mostly internal changes like in the dev version.

**Comment by Croydon** [comment]
Also thanks for exactly 15.000 downloads so far :)
![15000downloads](https://user-images.githubusercontent.com/1593194/31050384-266c978e-a649-11e7-898d-40f6432964e5.PNG)

**Comment by Croydon** [comment]
I feel forced to remove the compact mode, which hides the text label and enabled so far an favicon-only tab sidebar. 
The WebExtension sidebars have a too broad min-width, making the feature in it's current form useless.

Anybody with a creative idea to keep a similar, space saving feature?

**Comment by bwinton** [comment]
What about keeping the favicon-only tabs, but wrapping them, like 
![this](https://user-images.githubusercontent.com/159571/31308441-0496216a-ab45-11e7-8d70-921b731f1a02.png)?

**Comment by grahamperrin** [comment]
> … wrapping them, like …

Personally, I'm not a fan of arrays. Maybe because … 

(A possibility of extensive discussion. @Croydon would you like to spin this into a separate issue so that `#13` can remain reasonably terse/focused?)

**Comment by InfernoZeus** [comment]
> Implement correct sorting of tabs - keep it dynamically up to date on tab moves (83d1e9e, 0.8.4)

I'm not sure this is always working. If I open a link from a pinned tab, the tab opens at the start of the built-in tab bar, but is placed at the end of VTR's bar.

**Comment by Croydon** [comment]
@InfernoZeus:
> In fact, any time I open a tab by clicking a link, the tab is added at the end of VTR, regardless of where the tab appeared.

Thanks for reporting! I actually only tested for the tab order at startup, when existing tabs are getting reordered and when blank tabs are getting created. I didn't test for opening links in new tabs.
Should be fixed with v0.8.6a3.

**Comment by Croydon** [comment]
In the current alpha version pinned tabs cause that not-pinned tabs don't show up which already exists at startup. I'm on it...

**Comment by InfernoZeus** [comment]
@Croydon Thanks for the fix, will test it out 😄

Hmm, I just went to check which version I had installed, and it already shows v0.8.6a3. I think Firefox must have just updated it for me. Just around that time, the sidebar glitched out on me. It's now only showing a couple of my previously pinned tabs (2 of 7), and a couple of new tabs I've opened since it glitched. Looking at the browser console, I see a bunch of errors in sidebar.js:

```js
this.document.getElementById(...) is null          sidebar.js:416
insertBeforeTab is null                            sidebar.js:471t
his.document.getElementById(...) is null           sidebar.js:416
TypeError: insertBeforeTab is null[Learn More]     sidebar.js:471:13
insertBeforeTab is null                            sidebar.js:471
insertBeforeTab is null                            sidebar.js:471
Error: Invalid tab ID: 631                         ext-browser.js
insertBeforeTab is null                            sidebar.js:471
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: ;!function(){var t=0,e=function(t,e){ret....   vertical-tabs-reloaded:1
```

I don't know enough about how Firefox auto updates addons. Does it do a live reload of them?

**Comment by InfernoZeus** [comment]
I tried to restart the browser, but the same behaviour persists. Only 2 out of my 7 pinned tabs show, and no others. Only newly opened tabs get added.

I tried enabling debug logging, but it just prints 
```
57.0  index.js:288:13
20171013042429  index.js:288:13
Firefox  index.js:288:13
```
over and over and over again, multiple times a second.

**Comment by Croydon** [comment]
@InfernoZeus 
> It's now only showing a couple of my previously pinned tabs (2 of 7), and a couple of new tabs I've opened since it glitched.

That is exactly the bug I mentioned in the comment above yours 😄 

> I tried enabling debug logging, but it just prints over and over and over again, multiple times a second.

Leftover. Removed now.

**Comment by InfernoZeus** [comment]
> That is exactly the bug I mentioned in the comment above yours 😄

Whoops! Although it's also hiding later pinned tabs in my case.

**Comment by Croydon** [comment]
Tab placing and moving when pinned tabs exist should be fixed with v0.8.6a9.

@InfernoZeus Could you please test and provide feedback?

**Comment by Croydon** [comment]
I have implemented a landing page with update information. It will be opened once after the update.

![vtrlandingfull](https://user-images.githubusercontent.com/1593194/32695798-df8bb8d8-c766-11e7-9d7b-4d8059b6280c.png)

**Comment by Croydon** [comment]
I just implemented drag&drop.
It's very basic right now, will be improved in post 0.9.0 releases (#140, #141).

**Comment by Croydon** [comment]
And just in time for the Firefox 57 release today, this is finally...

# DONE! 🎉🕺🏼🎉

**The first stable WebExtension version is now on AMO!**

Obviously, there are still a few rough edges, but I'm expecting it to mature fast going forward, after all creating the basics was the hardest step.

**A huuuuge thank you to everyone testing, reporting bugs, using VTR and to anyone being patient when VTR did break in non-stable Firefox releases in the last months. We made it.**

**Comment by jonasflint** [comment]
Uggggh. Congrats on the release. Unfortunately I don't really have use for the addon for the following reasons: 
1. Compact / Icon Only Mode is gone - this was the only reason I even used this addon. (I loved it for this)

2. The Horizontal tabs are still there! What's the point on having two sets of tabs taking up space??!!

**Comment by bwinton** [comment]
@jonasflint:
1. shouldn't be _too_ hard to add… I did something similar in [this pull request](https://github.com/eoger/tabcenter-redux/pull/106).
2. is possible with a userChrome.css change, as described [here](https://github.com/eoger/tabcenter-redux/issues/15#issuecomment-334548845).

**Comment by jonasflint** [comment]
So @bwinton will you be implementing this?  It would be a life saver!

**Comment by bwinton** [comment]
I wouldn't wait for me to implement it if anyone else was interested, but if I have some free time over Christmas, I might give it a stab…

**Comment by InfernoZeus** [comment]
@Croydon Sorry for the slow feedback re the issues I raised. 

Can confirm that the issue with tabs always being placed at the end is gone.
I can also move tabs now, but the "faded" preview of the dragged tab gets stuck briefly after starting to drag - is that expected?
